### ISSUE TITLE
Research Protokoll hinterer RJ45

### ISSUE THREAD

**Issue by peteh** [moesterheld/deskcontrol#2]
Hi, 

mein Tisch hat 2 RJ45 Stecker, kann man darueber auch komplexere Befehle senden oder ist das ganze wirklich nur ein Mapping auf digitale IOs? 
Es gibt ein Tool von OMT, mit dem man den Tisch auch per USB  vom PC kontrollieren kann.

**Comment by moesterheld** [comment]
Hi @peteh, ich hatte nur die einfachen Auf-/Ab Schalter zur Verfügung und festgestellt, dass sie ganz gewöhnliche Schalter, die über die drei Adern im RJ45 schalten. Das habe ich mir damals für das Projekt zunutze gemacht. 
Ich denke aber schon, dass man damit auch komplexer steuern könnte, wenn man ein "richtiges" Steuergerät reengineeren würde oder die Specs kennen würde. Da kann ich aber leider nicht weiterhelfen, da mir das abgeht und ich mittlerweile nicht einmal mehr Zugriff auf einen dieser Tische habe.
